== 线程级并行

在多个处理器上同时执行多个线程，提高程序性能及吞吐量。

处理器之间共享数据有两种方法：1.所有处理器共享一块内存（集中式共享存储器/对称共享存储器）。2.每个处理器有自己的内存但其他处理器可以访问（分布式共享存储器）

=== 多处理器体系结构

=== 集中式/对称共享存储器体系结构

多处理器需要解决缓存一致性问题。

使用监听一致性协议。多核CPU各自保存数据副本，如果一个核心对数据进行了修改，那么其他核心保存的数据将过期。通过写失效来保证数据同步。

==== 多处理器缓存一致性概念

==== 一致性的基本实现方案

==== 监听一致性协议

==== 基本一致性协议的拓展

==== 对称共享存储器多处理器与监听协议的局限性

==== 实现监听缓存一致性

=== 集中式/对称共享存储器多处理器的性能

多个处理器共享同一块内存，处理器之间可以很方便的共享资源，并且处理器之间通信比分布式要快。但是处理器访问内存都要占用总线，当处理器数量较多时会因为带宽不足而影响性能。同时也容易出项竞争冒险现象。如果内存损坏，会影响整个系统的工作，稳定性不如分布式共享存储器结构

==== 商业工作负载对性能的影响

==== 多道程序和操作系统工作负载对性能的影响

=== 分布式共享存储器和目录一致性

集中式/对称共享存储器体系结构由于总线带宽等限制，处理器比较少。分布式共享存储器结构则是每个处理器有独立存储器，以允许增加更多核以及处理器。

同时为了减少带宽占用，使用了目录一致性协议。每个处理器在写数据时，只对目录进行通信。目录记录了数据的所有者以及一致性状态等信息。目录与存储器一起分配，使得不同的一致性请求访问不同的目录，从而防止竞争冒险且减少了带宽占用。

==== 目录式缓存一致性协议

目录式缓存一致性协议能有效减少维持缓存一致性的流量，可以扩展到大量处理器的系统中去。缺陷是在有较多处理器情况下目录储存开销较大，且访问内存时因为需要查目录，可能增加访问延迟。

当一个处理器请求访问一个内存块时，会首先查询目录以获取状态。

|===
|写操作|如果其他处理器内存块内有缓存该内存块，那么目录发出无效化消息通知其他处理器使他们的副本无效。

|读操作|目录更新共享列表。
|===

==== 实例目录协议

=== 同步基础

原语不可分割，要么全部执行成功，要么全部执行失败，可以利用它来实现同步机制以及减少竞争冒险现象的发生。

实现自旋锁：

函数不断使用原子操作获取锁，如果已经被占用则一直在循环中自旋等待解锁。

适用于希望短时间获取这个锁以及在锁可用时锁定延迟较低的情形。但是自旋锁会占用CPU资源，不适用于长时间等待以及可能出现死锁的情况。

==== 基本硬件原语

==== 使用一致性实现锁

=== 存储器一致性模型

存储器一致性模型保证了在多处理器对内存的访问的数据一致性，不同模型决定了处理器如何对待内存访问的顺序性，从而影响程序的正确性和性能。

==== 简介

|===
| |顺序一致性|要求所有处理器的而操作按照程序中规定的顺序执行，且所有处理器看到的操作顺序一致
.4+|宽松一致性模型|完全存储排序或处理器一致性|仅放松W->R顺序。保持了写操作之间的顺序
|部分存储排序|放松W->R和W->W顺序
|弱排序 |放松所有四种顺序
|释放一致性|放松所有四种顺序。区分了用于获取对共享变量访问的同步操作（标记为S~A~）和那些释放对象以允许其他处理器获取访问的同步操作（标记为S
~R~）
|===

==== 宽松一致性模型

=== 多处理器测试基准和性能模型

- 性能模型

- Roofline模型

==== 两代Opteron的比较
